sudo: required
services:
  - docker

before_install:
  - docker build -t yantolee3528/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true yantolee3528/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: ap-southeast-1
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-085260387626"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id:
    secure: "sm2HpJCWnUhRrb32uH9G7Im6ONpF6St6H9Qc6u4PvR2348ZrVzKI2tlHC/yeqF7zaICl62eqFW7fxv/CEN+DmVJDWvUOXrYl+LKaUb0sO0Im+ajGwrpPbHUGtVPZg3sqzJItWQjpXLbe6FVqm1902JuWiBJc7uK+zGWMoydKaATrliO3uTzp29vjBjukoRSvLOj5xdF9/3I0gzWbzn1BaXRtf6212gNH4WCKcQLfKpLqH+KyAhcLKzq15Sy5wZ0GY9mR2JhZAYFcZAelJS56nMlyKXnlwmTH610cwEclBgjLtvtJKTBHWBYLB/kcwDol2QHSJW+AcuEEAN5+80u/Fm1NQLKebrZijLZt6MvQiMVMjGOQ9QSljwNzzZjpXxgLtwWkkTSAsVsGeKG7SL/E0EHGp/8NnGT19ZYWfKneaE6rPRl6tHn9HR/YFyK8yNHq+ivNDU1stPzA5sJnjoAJpzWSMiD7EEVVFs6NHEpc3CCNNRH/KaevgiwCxwL0U1anuP4yQm9+sUxD9EeeG4uoWoLnHVZZjMW2bG5vcX1SPyk7Ucx/WK+JZVxS+gq/r9qXs7QbCJg2gy6ZOcfCOEWRyj6qFCwzLiBUy53eWDRyfJ5NS1EdX+4F/nxGTfYdTc9sDurg3EFf8zFkl1BHdHBQ3eQP5P0R18jwo7FPNur/4Oo="

  secret_access_key:
    secure: "dJf4UCQQaLPWZTlcfpnuQk4a7dqYHHu7arTUZBOwPiOrBoXgEB7dGq0riVf3DnAlDBN69pfJitOMQx4TY39rZAjLioiYphekvvKS/rM1w8xWUjMrmXdaNqXiflb9aJfaOjRSi8oiDDNQEl+xN646BnqABzePb143aHq7IdkIaBG4WiljMew7z5K32Sv4Uno6vE6uMJ7FX2clzMLt+YDdhNsRkFRXCsXfP936mw1sdMs3cJssNkXA6UUKx1Zks0huSHVAyzgfe8bxDuNya2r7NF4yrOZOYXmY9nzK+DzbKB3e2g2Vmxum8ChurqvYD8a58Z/oKhYRYcRyes87TEnlUrxIj3RQhhMXc1DAVov8aVAdKtvNZXaECaeP2k6BwBZfqpKIgSIalhWC/3QYYIzZQgkCywqn/aJ3wo4awfrF1gVipvZwEoseShsr1VisLBUPojiiMhMxmfT4efIFJrMtEa8/OoIwu5GHQHuG69KCxyfeN5xAoU7JQJBtkCS+sAwAbKGtZ6Jh5GBePjLAl/bOKU7FiCCRXrcvvZLyHhZpEoQf3mDSExqYomvBIH9e3p8/hKoDgAF0BCFkCpaUeDRu1/F0a8Xuy1Lm0YCom+8UDjvQeFrHzncyV7rxFy4ANK0GrqP403rTyi3a4BHh9qjIFRkOe2ER/On9lGbj1Wr8dhs="
