sudo: required
services:
  - docker

before_install:
  - docker build -t yantolee3528/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true yantolee3528/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: ap-southeast-1
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-085260387626"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id:
    secure: "yyScoW/JD+e4V3qZbFh6kDDNGDuqKTVHHkPtOQoiau53TyJAFYBHHeY+gkN1dq7tuKB6ReMO9cQjJ5CdKes4IkGM6Qz2cdGHtOqrul2i7IWF46cpQigie+MD5xa8gfyoNzHxJQZ0yJW6eDRRhd0u9EwuL2VTUnzPZOd4hjke9XfemqfKwjCVkYBEhMPB9rLeqSM40q1WqHOMSJNvBx9dEU8Iw91z2bYThqFuDInlvBYItzTJxozvzr0bRkmJleAHS8p9fArjMx0WlrTxG58HW+ZKf7ggqGCcCpcEuMTS+kg/5/5JThvMhw3FiMhlfdit3DFFIWdY5kZgf53dqNPfsLAIslDN9hEvFjZ198jga68+E4KVMbEwOeE6yXPsi841AWPrpWG/AfVmyT1cGJzznWQ22/Fj+lzE276i/GVbLKdhoOe93OiSO4Hi6CcKlFagA2JryNj/v/8TTI4DD4PukWppO4tLQFABP2xlbU4iS5ixh58L90xXMmfZ+zGYh4DM5mnQrBkZzQ2YipJlNig+K72lJnyqj90x44tRSFCZAsBsPfk06pzllnbdtDvMKdYrBabOaPWeo6k5KzWZ2b5We0RCNmmGsAoilJCw5utn3UJkyGH2ksw8OIoXrf59DJyBXYj6HHweBlMT3NYU9zfv+Q5tHmA4B+hgeAm2xXWJ868="

  secret_access_key:
    secure: "II1m02uqwTVH2sIByOxOOipF5BvPZyHyO3Sqhte/5+p7xNfyASZj8cmNCRyB/DHalqqszxn8UqjJ3YLsZD9CHXn+3hUZodUBdgbjnqUSb02SeIcx7IMYq395GuTZmrImb0k1wGxTSw5O+2cdOpDl2HsPaDmKxhibuTkEoSs1LVbGbRfurq2ohygCEj7opDSDTFfS3qxLjyLZS3HLWMdwFuxLj6QJ+WTFYBDg6yJqigx5YKN2q8I0VkbvlvYJinlBQhfJ0xxBNCPAE+nCm/YCNoL3ucerbPNTEm7tgojCS++HSVXnsuNDDk1+df2DHWhVKZ/Sx2MSI0Hnz5jpbcufHHPjmduzH3Yf/9Rl/wwwZySr/IZRV+lPjP/gaqKZw1E7M6Carv4L2bVIEt9KBXDJ+OgjAsWiv51HBmQ1WnS57Zss+tSxW4t24J7LNMGiRyfsCLtr5yO5lvjfkW5yAhD31jB043k+3O1LOPbFncSycotymVCwLw8SbtvY0EPz3d6/7+QKG6j6KbzV2Afs5i+rqFb00oSi6zvXi23TH2/7Mx8J0e8n/n+2aif8Mq86cIY5gcEjfpIm6LmhtZEqZpAcJRLplsNKq8ri5RaqW4IG9iRENjnS+kixO1OzkCxluL/41SWoDo5pS9J+ZqeVKGbjr5B4Qscn27a/CvjiIRivX8Q="
