sudo: required
language: node
services:
  - docker

before_install:
  - docker build -t yantolee3528/docker-react -f Dockerfile.dev .

script:
  - docker run yantolee3528/docker-react npm run test -- --coverage
